#!/usr/bin/env bash
# SPDX-License-Identifier: MIT OR Apache-2.0

# Render assets/icon/lightphotos.svg into every raster the app and site use:
# AppIcon.icns for LightPhotos.app (bundle.sh copies it into Resources), the
# favicon + apple-touch-icon that index.html links, and the README wordmark. The outputs are
# committed, so only re-run this after editing the SVG.
#
# Needs resvg (`cargo install resvg`) and macOS's iconutil.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/assets/icon"
SVG="$DIR/lightphotos.svg"

command -v resvg >/dev/null || { echo "resvg not found: cargo install resvg" >&2; exit 1; }

ICONSET="$(mktemp -d)/AppIcon.iconset"
mkdir -p "$ICONSET"
for size in 16 32 128 256 512; do
  resvg -w "$size" -h "$size" "$SVG" "$ICONSET/icon_${size}x${size}.png"
  resvg -w "$((size * 2))" -h "$((size * 2))" "$SVG" "$ICONSET/icon_${size}x${size}@2x.png"
done
iconutil -c icns "$ICONSET" -o "$DIR/AppIcon.icns"

# Browser tabs and home screens don't want the macOS grid's 100 px margin
# and drop shadow, so the web icons crop to the tile itself.
tile() {
  sed 's/viewBox="0 0 1024 1024"/viewBox="100 100 824 824"/' "$SVG" \
    | resvg --resources-dir "$DIR" -w "$1" -h "$1" - "$2"
}
tile 64 "$DIR/favicon.png"
tile 180 "$DIR/apple-touch-icon.png"

# The README and site header show the icon beside the name. GitHub serves
# README images through <img>, where an SVG can't load other files, so the
# icon is inlined rather than referenced.
{
  cat <<'HEAD'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1020 300" width="510" height="150">
  <!-- SPDX-License-Identifier: MIT OR Apache-2.0 -->
  <!-- Generated by scripts/make-icons.sh from lightphotos.svg; edit that instead. -->
  <style>
    text { fill: #1b1d21; font: 600 132px -apple-system, BlinkMacSystemFont, "SF Pro Display", "Segoe UI", Helvetica, Arial, sans-serif; letter-spacing: -2px; }
    tspan { fill: #e07a1f; }
    @media (prefers-color-scheme: dark) { text { fill: #f4f1ea; } tspan { fill: #ffa447; } }
  </style>
HEAD
  sed -e 's/<svg [^>]*>/<svg x="0" y="0" width="300" height="300" viewBox="0 0 1024 1024">/' \
      -e '/SPDX-License-Identifier/d' "$SVG"
  cat <<'TAIL'
  <text x="310" y="196">Light<tspan>Photos</tspan></text>
</svg>
TAIL
} > "$DIR/wordmark.svg"

echo "==> Wrote AppIcon.icns, favicon.png, apple-touch-icon.png, wordmark.svg to $DIR"
